---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-shows
spec:
  storageClassName: local-path
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/shows
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-shows
  namespace: sonarr
spec:
  storageClassName: local-path
  volumeName: sonarr-shows
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
