apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drone-secrets
  namespace: drone
spec:
  encryptedData:
    values.yaml: AgCC/16gGoHVDgkzJwVCZ9pKVe+PBmf1pckal2vbeljNaOIG3lRGhLQieNQv04T6aUNjAenbRrsBeEPsAuN2WczZ4YEL3+tnX6BuJ0VLsE/gnw/1oDV2qLhQ10R8VZtDlLVtq1kJFJwn3oKikhKt2yfWhLO2dH4Qn0aRwUn1KrGTRwd+oElY+jgyUIlIfQREerVR8NLMymwmYihVvblankoizaJYD+zx/jYeSkpKjSGcrpFcj2rNnn0Im3U2Z3Asnyy+bzAbxkVllzG7EVs0U1TDgHB/LmqIlv9vmVX5XqSNFpYaZnD/XG4Et3BQ4dgelASVSnO2vSdOBFsck+Zw9HOEodfqHwihRgE2Y1Y9llDIVxa0PdKT4qPCjySrNV4hrD1aOH6+ALQXXkwcp1uvHWV4ukRimgwfKkXQaJ6VoI3Sz4AKbnea9t0ZnA2abBK12zHEvMH8nryUFqKHeH1SvTdjtahzekjUY0Jb9eD/0BsrRbuQuz9+K/oJYdnHutfCV1AJvktV5f9kj55X9xd4Dl+JLdcGhonYXV6m6l5kg09ZUw3IpqKZ+84U5dYCxxr/vAPl4M8Qtgsg8x3lXCA2mZ1tEBygFrpTUm2QK/HbVAxWzX2ZiPIqxJMeZ6YpmK2wuXgMPKk9XAmyp7HkGJWEoZzo7xudq5OGIzgnLQmdVtlrxbtUXt5qPnrE/8cD6g/Yw5Xlg37UHCmHKZPsyg+Y+75mQ75D/PjrZZqXe6ypDoVbigupN2V8SN6Ab69SA+Dtb/rDfR0bj1QjgDrMv4StPOrl01FJMlNPHi5SzLWmsDQ5ybkFWQTS9yZBIygpaTWlr+rneABt3DcK8LCKymW6Dt1uoJCA5PeKMxdg/I3zjTGmc6xBjCtq12uUpg6ppTN70uud471RN51LOW43Vt/GjaQGv0/D+N5LNOrceo/ecPthx9DAvLAflCjZXd15/GauzbdKqS6l7gFtWY8RQlhFNEW3ycg6oc6jrnOLjGnOoGU7NEjdhz3UNMgI8OXV6tkJUuZEIpSjIbmb1Z1QOiUMEx/NWG8EOjFlwdC+m8haBJ2SGKHXJOdMG0bFFvxIEp9oT2BMlSUhyoQQRztUuUagsywAnEQ26zNsmGww9g4HbQy46bszt5KL8E7cDG3sZPN6f7IsQEVAZ9HNWcPV+Ls3m3XKyIOibCj0ciWSqUA8xy6rHtm8QtU7+sRRtKE=
  template:
    metadata:
      creationTimestamp: null
      name: drone-secrets
      namespace: drone

