---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drone
  namespace: drone
spec:
  encryptedData:
    values.yaml: AgAD/qj6653AX5CoqIFkJ4Q+qFGCCtFHlDSkVzRh6YaLfaPXxcMjlM/u3gcyjRqsMD8DeuGxkgZBGO18Rm2uorE5vcXoX9PlZnf4n6zpXw2sHRHflipsKXL0I4z75VEylbU+jhkSybeMS5Awqr6+WCvBwIwcMNJfZ4NcqD/Hf90J2Ip68bb27Kk7IitFMiUTJJLtucvpvwWjpqXMJJKXsDTwZlnhOHOjY8xmJTh2KXR20geF+jBmLhmSBL7nRVaLgcOzlvnT78QWYJZANmgev4AQNQDvZCgSJ1y1WNxpvX4pY1vUjP9tvwUAsj38grw3aiktRb0EJXUL7sFZtiUThWdXfJxsHOYfJKfN75J2PH2+kLHrMrsZCfYkwqkt9CuO1F+JzhK/sElbVq1fXXeamGLZG1ZUgT2Rth9Kh6Z+lb2zhZ4HUwa4/KZV+3zGranv8FAnzlmAVQlMzQl1RleSeABrsOSbemxHFbMYUH8fvgzt99eFdUSwbKLVRcIhkWp9NCi1llsmsW/tL3qw1k9mPr+4EUTLxurZ5iFarbmokCh5opSH4rQdSLfhUo27nYDfgM3m60pclfWliS3oz+Jj36vIu3fB0gBzlqNlf5KY0QiuDUsxGXtL+r2zveDzFpEANXo7FQrqonHDaoKJsfziXQLI4v9/aI/7JWYaR3pbxLA+u242lSNw7jdIm2/SzsqCnLeYeYGo9cE90T/RIC58foWJyKq4PXkxgwo2die1fttpjLGzv2lMETuyEgAJkQ5ryYhcqZu3Ycx9E5VxuGdFwNdF2Pzcv0BwJ2hbUtFmcZxuVD8f1CntN/8p5hvCUnCscmi8lOkdyP+DGvpdCpB4HjGa1PbX0zm1TNSvPsk6N4PjZ9ArKUS1621IGgF4RGbZ3npqWuqIqS2U9XyZMdorJOupg5t5pRzjq8woGnXzG7tBEFqDNNclwI0k4YU/2FzZrI+HAj8b3Jny7TgOSYSA2nh/8QLLHAnAe8tlXfTG+c+Ui9y/6wqTEL1Km4393wjRgVtwdXTEpr/YUDaQ3S+B4MalrJA71HNYt6MHlaNXdYRCXuPy4KlCaae4jss/pXk4H5iCBKyf4/ma6A0qJ34HM7Y5ZKYfll0npOu2ZqAtCBycX55DMZCZYkETT2uUmsvW2M5MjWtV+OIrs8Gr7rhsONtnOdbKzK/ZYp+K+G7bw+ZpvYZlEAZ0YoF5Tr1Rdys94ZIElqfa
  template:
    metadata:
      creationTimestamp: null
      name: drone
      namespace: drone
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql
  namespace: drone
spec:
  encryptedData:
    values.yaml: AgBwF6eti1yag/sQPN7X/SMb7Kmmw4Y4mDAeZmnyvLluOKCsiwhQM3OpR6FDLuVGkCthZXn4KBJJD76pqb5WHINw6oa2gvFEqeMiCH0t0Kg7KBW3V/StDUs04pAeO/UPO+PhKfW+tNtmVwCZuVYBNX4yhq2LCWB5DnCLSlKQFDl+exeBEFZcIcA7YqQMaVygMcOjTuaZ3Pw3hmo88eBTo83h2Qt9tOZKULoNVhKeExW+Gl0QHM8AQgq3g0PPNmiOCpiTUibYD9hryiesw0Axl0nQfFk8uO98E/Mj5zM07jhhgULF2HQx+ciT+FaKMeAcy14cH09gn30B3ZTzd8PoEhW8wGAJ2OchBJ8ctqO+fZSaTcMaZcKicLaex3J2QFDlQV7m5QoXENE1ZRJayfsbp9I34tFsGg8C7QLAL7ePbLwOq8LdVJIqg1z4OlAsOTjSJU9JkZzLge+jeUgIdqEJVc5HrSDgmWmTdbzX5SV5pdVDbSfYXAKvcAjWUNe7bq/auXp5UDgaQj3xp96DWb/u2BVHTOQMXfoJg3vIwqRl557lwrqbUdhybDQfE1Cc6hrWG3PeIwa984zHi1q7lebw440+r3ztnscxcdJPDBrQ4gTabiKjom02Tdmeo6+zVr9wGkZepjnvTHL4Dk1iVpQQEJH8FFTY782i51q6uF5X7uGiLbDyhRM4Xmd19bS2ZuhfUFVktt6KIopwpqypNMEPw1AD+BqjuSpmJCBswS4yHrmL6ZvTxdgStBM3KwfzwblGY+OF0pN1ZA9YF5LTImjmmEigf3OlE8rAlqCCI4+w3XiqXhhqYgXr/ULTCbAP1TQma+kg
  template:
    metadata:
      creationTimestamp: null
      name: postgresql
      namespace: drone
