apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drone-secrets
  namespace: drone
spec:
  encryptedData:
    values.yaml: AgCDJor4kEbhJKnGkJlx3fmZSLJpEtUd1hZBY4E56zzDbgFpKnCDAh8x9zxJrQGcLmjSnIJW3ZaDwoEpxy9io7/0jEhp7uLNMK4iULJj/PeHPsBp3OULYlKT0V6UHt5loy9ggjS5x5f6xc1sGmjRd9jEJdfy+BlL5HKbfubhhGc/iAQQlU5by54mg+ospPl0znMRnTnlqSO2MQw2yhNzcq08ZzkgjV0X/R7ZLNiEVoB0bnSjX7tAfNpJNoPErMSp+fgZOHj8zZxhOUev2CZQL17eZ57LkJh6zN6i0s3A6aOGPTpS5TzqBVEFUM8uBMbNOfo/bQjXhZg81GcvIQrZ+VEPMhN4VlxM5EH13W8CsR9waw7xtVq8ClTcRxWGhUvfEmI0VNQHYP0Xackxy9VgWbnOwuAaYtZBLE9Nmt0i+b1NrTXx/5OZQV+9w4koxUqEyaqCSoggDpVC+sseUyIiZWk5ZeazM4zSu/VcMdUvuKi/4uzjEfJC64g2Qrtpt29T26vbpHFsBL6xMOUmfVS3lO4OnwqzU9aJiYWaOu7H1AA5P014DMRGTVgp1ZAGq4baYt7wkB/FHHunx0jJrtlcJRqEAk1WEcv52zy8vqQUhyseqq1ba3DR2U2T7tOOXlKZe1ag/4dzPugpfFT5/X/hrxLPBIsc5FM78KN0uRxsQF3/N+rkaHqJstEIfPoFnjlaB1qqSz9tukUUNXtaXi4GRZTvrBmhLpMm2FCQWZxg3iGhaKgnNvrDiv2tbfSLhaH8v1JAZr6uNYtGM1dVXVlzpm0RRrya8Xmb+HKLsrbuDp9n0J/Hc6X1vk9e40yLyktCNbhX3rFG7sh19wKYPr4KdQnki23I3V5WZK0EAdv6hrFZiPsnH8JZ9RKLlRL0ON4RBrr1jJK8K91EzVW/MDsxQX9fgLoTGgZB7VFOlIKD9Q8C/pnaDICdFdAuAlQp3PnLf+LYHc2GIs5hp5EX928YzGnh4HBqDuFlrs/bgrfQNjx/alE8lt9UUyXI4JYNJqlPxJMAM3FRG0krUjE5osScotle+/HmJmNXEEDVaTYWSThKPVIPcQImib/F57NZz4WIEwThRbXqm7HDiPuL6JJNodvM2SObC1RrB1hnRpBvXr2G1DOg3LWb7GyBU7zWlavaKXKiSO7b7Yc9S1C5AgaTilmPrDi/1+LqwgK9v3mrGECDekAMHpc+lk7GKY96k87x4x4pCVdAa2Efk1A=
  template:
    metadata:
      creationTimestamp: null
      name: drone-secrets
      namespace: drone

