---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-drone
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/databases/drone
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-drone
  namespace: drone
spec:
  storageClassName: local-path
  volumeName: database-drone
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
