apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drone-runner-kube
  namespace: drone
spec:
  encryptedData:
    values.yaml: AgBvqAChH9GyDeVxyIek0tiqlTAXzkp+fM7EWG5kNTzSYBdtk3xMASyDWikXxYKSjHoKcOhd0+vHmndp244c8knvqcOZ7nqZh6dHgnlwYzXIZbuPO+1KTRjjTpY2Rneuq+F9FiMedzPb9NOYdZqrINaPryFS57BQbLdv81LwQ1853STVI40xZJRJrD2cApQOZ+SVM0r32scky/UTm6mly04YRlIjtZZsBW7IHpk1Nqg9UjDix603BCdct988U6pdMo1zwQwQeSs940MmfeFjyjXxdm5ZWhDf9m4azOpIlA7OAULUEGjjf5mmheumxZVE0WnhpMd0H1RYD2scOFJZLugHQzW3NnZmXIRLKMVXh35tm9I761o6Kp0QabSqbWYdmbIJus7Dyog0M7sARNfasMD2Xk6SOH7JSUattNyVGTu8t7FwD1YeAbAwFQtzOH2G7AyCo1UPNQfqOnH4Z0wwfOWwWuo8eWZPDrHM9NDui+E3QUI4shQv915tFuGbLpNLvZIEmCn8uvW2j9EqSwIYqqMQQW58QofX3RIjOkIuWtnM1w3Plr4SPsN2FaOw+PVjAu/ZXkNlyTxISwjiJr/r5rYJpaaonTPb+aQRtKsVQEDPyIlTiz+M8SDcY+oSfQi49Y14PBFtddqngKIlrcBFfMxMmUytlpSqkf1GiZw2W16k3JQzipELQHUz5UAQWziNmRGviv5gbQwOWwcEGe02mWYhKoQn8a23zSXG7nS67JtKtEuEX6ovju0AcqqrngaG+6Ss2sVLxjWMOWdz
  template:
    metadata:
      creationTimestamp: null
      name: drone-runner-kube
      namespace: drone

