apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: dendrite
spec:
  encryptedData:
    values.yaml: AgDAAj9UpFXfH/c7IO1eieh9bx4HfKVKQ23alL191CpXznkk7NVgd9gz7gDVtOfaJq5dsmkTPUjVzgHFkhwpBg9xK9ry2GB/q5KLvl03MI/IEX6WIEIStm09+eUzur7vLifgIk9840DSzdV4iTUubP7sl6giz8TLNEcw75DSiMHkc8ZML/mrLu+TbLVM5x5ptqF5TyyA5MqTFKRqirbmUgcLnt9+5IoKhFSL1zA1bWpYJkaVZXLr1grqr5HMJny4ehZUrlF8vFgJh9VSrZPa/yCTFlixOuuzwM1TSGG4+qX7H4MBVnZuEkhxrJTV/umnzNjyL/JtAj6kqSEMkycSYI/dw/ig4rAKNr4Wqob8vbhayUdeLNFVaexMJVq3K+i5gC28GEJZdm77LJb8UEl7Vho24D8mby9inPtEnsB3EljzWGh/wfpma5NKGUA8cDDMjwJkawXTWtmt4QkLziesFw/SQzcWjhT+4fukaE7WJYG6ax1gAxwgqNvoNiw1K0zQTjIf7d1jhnd3xvsyGahHTm/YSXTrfxN3RSlcn+pF3ziqVjCYu8/tXWkah4nQInWDZDSxdZWZsIAO+eEgP9ZihqtKt7UK6y3ibWiHI/vHuf7sRNZOzQFHeEKiNowv7IpVonQkBtxNiqOCYP7ahxQg7TapdMOSgQcgjwYAEbHFbwYxFdt8aIt8VbxBzttkIQ8sjkYGChoXoavlAgft0dlcxt6gL8ZSNq6jawhwpQfzWKvYRVYMI3Guj5NW9qBQ7V6L+pgaX8+AoOGps6jja/k3Tj97wbwciCP3ScYPdyRM1ptwfPqnBhBvBAKPr5nZjL2juLVdu3P0nQDW
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: dendrite

