---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
  annotations:
    fluxcd.io/automated: "false"
spec:
  test:
    enable: false
  rollback:
    enable: true
    retry: true
  releaseName: gitea
  chart:
    repository: https://dl.gitea.io/charts/
    name: gitea
    version: 3.0.0
  valuesFrom:
  - secretKeyRef:
      name: gitea-secrets
  values:
    image:
      repository: gitea/gitea
      tag: 1.14.1
      rootless: false
    service:
      http:
        type: ClusterIP
        port: 3000
      ssh:
        type: LoadBalancer
        port: 22
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - git.ssene.ca
      tls:
      - hosts:
        - git.ssene.ca
        secretName: gitea-tls-cert
    persistence:
      storageClass: local-path
    gitea:
      admin:
        username: sseneca
        email: "me@ssene.ca"
      config:
        APP_NAME: "sseneca's gitea"
        RUN_MODE: prod
        repository:
          ROOT: /data/git/gitea-repositories
          PREFERRED_LICENSES: GPL-3.0-or-later,Apache-2.0,X11
          ENABLE_PUSH_CREATE_USER: true
          DEFAULT_BRANCH: main
        service:
          DISABLE_REGISTRATION: true
        security:
          PASSWORD_CHECK_PWN: true
        picture:
          DISABLE_GRAVATAR: true
          ENABLE_FEDERATED_AVATAR: true
    postgresql:
      image:
        tag: 13.1.0
      persistence:
        existingClaim: database-gitea
      volumePermissions:
        enabled: true
      psp:
        create: true
      rbac:
        create: true
