apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secrets
  namespace: gitea
spec:
  encryptedData:
    values.yaml: AgAx+7b/WPP9K9cJDwMH6+MZaP907Qc9R9K9yoN3AzIIW+XHIvbte3uMh1356gJ8iKI611BsBbODD95em2rRk7JkwlXWcOwmEmbVKlEIEmpbzkSJ4H13Nmoo8k2CDCGo1XgVNAf0zy4AuYAB1ecMsIj5OwYnyMb7saV88kE5utoWtppw9lFc+v8pIkkIvm/KVH0gNmqENu9y+vx6HXDr8grxaF3A1Q7OR5+aGvgwhaL/o1QIxrYivjaF9WtWGVT4XOL7Uywug69ZaIimGbPluryHmT0NfUAViClwt+IbNb0DubMfNURYxq5/eUETFdrGrdwUELAkuIpsZ7pQ0bGg3LJpyPuHEvbcA595wdVyjVoCK6gnNyB0ohWtiAgusr1xtr6vCAOivQUqfDc2me2tyaDXzF/E/gP0vL57UvqrzLlJIVFWmkbVNsKOaQwOQs01f0sz3muGpD+Jv3COJ0+7CrBNeEe4/OocImm+qErRna/2FrxM4kZaSzDn9CJtb1AtsoH+L3foVO0lcbsBoIRZhSYmerUVkLf2b2Ilql3JqW7ZTOw4C9jae7JEbBsYCXOsj6zuueOj+EdAABDY18rzOuenTbkQYcZkpHo29xCjnv9PmkZe8jrEj12l9oEBbshg8CBf7TU6ooPCAJq6CMOxfqtqFjNk8VVBFjFT8Q3gTQvhTmZCsTMU9eqGEpgB6uLmGkHhHI61owYzWvbH4FXQIhRJ1XxlzVZSTxCCgcD7VRmovlLI7ORiqtKiuZkEi4LTFIH3W//8d3gIES3k4jEeqE82nkNg5WkLbZ5ZtHq8aYYrwJE9EI20nDr+smM10ZANN/Xc9mGDuYpzj+d1JycwZAUXZCbb/I59nYI9FQPXZQ0xZ5aawgD/QCMcWxjJ8m8hW0/tiw6Qg7RYZOB2EdwpKyhGZqRs1YS84h6sfHkAxz+UYITl1zNRfPFMq92o3bSrRwCj0Az3MPzwi6GI3rxholxKOlI=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-secrets
      namespace: gitea

