apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secrets
  namespace: gitea
spec:
  encryptedData:
    values.yaml: AgAQneJIrd03HNSCLDG33AE2mSK2aCVumIBSMiSV62uBVSSYaiybbG6U86vLU/hOTKDaR7eQ4U6I6dM3+SXOPC7Pa5fyA9Y/nIldcxwnuGjPHNPX8Ss3FA7ZBA8Ay7Z1MXKOCjWkHIiTYAwm+9uyOuVF0JQG0ONQt27Nv8IaMK1YVrf9cbtyzN9rTtTJiMBxGyymu+q//nJrJZi8Bsrwv54OL6Ir2drx9i7jEjtJQCSxU73wx9cK7iy9iDJqHFgJMRB83UyoGjwI9T3T4vfzqCnAqUm44LaiR1TwDHNLDnrbzikQJ89B6TX6R8oTBBOL4iFjFhsnfCgtoFN/EBrd8X6F3jYyLm5p0ELEXD4ux9isaugD7nuvfvK0e9pf5rlH/61M3Mkaa+m7fvUnK8RvmzaSu4vbFgi48R6rDNCBC5ylhVbnEcnNOuofapjo8nrjD1DMZJq1kwjt1XM8NQLRTkOEGXWYkYHjDIlK32s8u6xwDS0Zm8UHdjofJdSoV4yja6522+ydfOj+y8C2dhktoZXEdjvbdMUy/q3RhTbzNcUnhdb/8drVWA1iLjbFe8V6nYFz6Uss/35xvKCAU6lbJSSqR0rpzwisxhJUxWizhjHaIkm5VQvd5kQ/Vi657jl0NRqLHxlEzEcf/SeEVSr+Qp6HZmRSbXZbsY80vCv/QJIl2FCtIOYy9m1N0Sl9p8ema5y/TI5EQGaHGBVQBZsgld682i9DKu7WTuiiozccHrW7o0K+QZrta5+EC9d7BFn5XbPLvpNjwFuP8tzEAkdmvLqEcCnUxUsNgb7inJ/GbIFVzxGjhRLLrzCi8Gk9B+sHqEOH+JSalATkQ9kHI/Kn2DkBUanpDYp01NnxHDSZSNZfaqSZJXx82j0jVNgH1OX0JdvW0k7y691kxi+WMrsFwglYTPqUcXYjBO8uiDwFtws0pK8cm+DCmLbUQYnItggihFbM4eWTEReq6yR8m0v/qLU/0qo=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-secrets
      namespace: gitea

