apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea
  namespace: gitea
spec:
  encryptedData:
    values.yaml: AgAwSkXB/0TC3bKYT3bjK+jcuLmHxC0lo4UuKm3/eqtIkMkfEqbbZcYGLAmaC/Ei3zlSGk731gRFheRQV47jJIwGSWKPsS/fVzS5RR5A5GjWIwESXVv+D056K8b52CjbMwPwtH+b1v4oVOvnAku9S4vgP2QCjN/3hh7dc8RpA8I76aOrfid45hwZqYbCFoMeKhfdNjrfNGOK2833l8bk+o86epkIVFoChcFG3+m5BmGkkB+7aViqH+CN4qLiDL2aH20tLxyos37ZDY7RjU0Hk2SZ369HOq9oozn30UaadcOo/7Wh0p4MKeOpqwaN1hs6muQ8uZPEQUVu8+bRkC9q3RD76dZuKbUFas2dCx6NcZDdNm80D7bVGRjMFGwlpd5BQFp+xGDCDWE1xopsMzg21t/eP7B0bvc9Mhj9urpG7dtKfGue2c4ad6Dt6ryBI0lHj9S3v+mE0eh0q+DxI0NinEZn8oJJ67mZg6qIl8/EhSp/Y2PyDfWvdRjiKegJkIZyWrZP0r2Bqschgyxs/q4fvaK+/MZG3jNrCv67H6zDembdInGAOJyvCFYlbGsKLQVJEWH3Xdl/6SLOYrAT7zcQunYQA143sgA65llOK4tHcj7fTbN75FF1xjiX4CpUcw1SyTU+pM7Eyd+PMG+S20uBVKscbRRdhn7+UvvoZhAPxLIX5Ceh1fx69YKrzW8Ss9RPvZAeDIWaaoM79PbQgJWrs1pCRrYDK6c5J+UISPOANk71D8aIViph6yBUg3PUQflVVbqqoHbJiDjNxqqlG8WkfeelsWCIkcgQUXZE2xgRtqLTgKjPZuzKSSviLMtdhMz689zFeSmQRkEEFsq2NS/TOckGl85wtbvl3FM3sgpMnQP5czZJHM0v/msF9crCM/czSncx/Uq3QQ66CpJH9NFvbcUBiyKsjjfpXuewLTqr8R4uiwM7JIsUVAxWhhr3ANFwLWxZKGt5a9xKhkXh2vWZW5dDH8s=
  template:
    metadata:
      creationTimestamp: null
      name: gitea
      namespace: gitea

