---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: regex:20\.[0-9]+\.[0-9]+-fpm-alpine$
    fluxcd.io/tag.nginx: regex:1\.19\.[0-9]+-alpine$
    fluxcd.io/tag.postgresql: semver:~13.1
spec:
  test:
    enable: true
  rollback:
    enable: true
    retry: true
  releaseName: nextcloud
  chart:
    repository: https://nextcloud.github.io/helm
    name: nextcloud
    version: 2.5.4
  valuesFrom:
  - secretKeyRef:
      name: nextcloud-secrets
  values:
    image:
      repository: nextcloud
      tag: 20.0.8-fpm-alpine
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
        nginx.ingress.kubernetes.io/server-snippet: |-
          location = /.well-known/carddav {
              return 301 https://$host/remote.php/dav;
          }

          location = /.well-known/caldav {
              return 301 https://$host/remote.php/dav;
          }
      tls:
      - hosts:
        - cloud.ssene.ca
        secretName: nextcloud-tls-cert
    nextcloud:
      host: cloud.ssene.ca
      extraVolumes:
      - name: photos
        persistentVolumeClaim:
          claimName: photos-nextcloud
          readOnly: false
      extraVolumeMounts:
      - name: photos
        mountPath: "/mnt/photos"
    nginx:
      enabled: true
      image:
        repository: nginx
        tag: 1.19.7-alpine
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgresql.nextcloud.svc.cluster.local
    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: database-nextcloud
      image:
        repository: bitnami/postgresql
        tag: 13.1.0
      volumePermissions:
        enabled: true
      psp:
        create: true
      rbac:
        create: true
    redis:
      enabled: true
      usePassword: true
    persistence:
      enabled: true
    startupProbe:
      enabled: true
      httpGet:
        path: /status.php
        port: 80
        httpHeaders:
        - name: Host
          value: cloud.ssene.ca
    lifecycle:
      postStartCommand: ["/bin/sh", "-c", "crond"]
    extraEnv:
      - name: PHP_MEMORY_LIMIT
        value: 512M
