apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgBZJVJac7x7wer8iPtJ28KX5UwRJ8r8w0TJMzUYK0bkXSQar/duge/M0p2Hw/ZpYnQvXKQvrS2zzWw2l0qpzJXAfBU/Dw+ssZM4lPYoAwbYJa/KBeg67ew3O0+EyieLO41GPNJRpn56mFqCtstUakJBLuOtyFbKpSVTxA4a5nr0925jxiMTEIFvfbTHUiHX8ytIpLrLcIbejgL193omwhqTegy9eiDEy7z10wd5CzzssaVL0coAMIbNfmMVx6OP4KF4erc8bno/GHRWlq/HLqxabVAw1IdfXOHlUXP38Jtn6D3m7RnykxF71RcugroIQnoiZuVSQsTY5H0EqrWSs4wqBe2JXU9RSMInlWou5yhfdSV/5eWNZMVnxW0Do//m/Nz8tdCvHDpsmw+XuuT3hth5rtAt50U8e/iMsxb4z77GJr6fBb3eKlCLRKbFXBlWMrXADvY895a9my7tLj/tv4EvbRjs+ykJ7TUOAOPie2+ZY1RezxNLe6dif1P/o+Eb6OAY8AOAy+RP+xj2wxWJ/WPvOT8OAUkisgtPlQDnzltYucVmNm1PIbxHa5io0I8n7HFxE2NoYZaugsEDnOJJj2ZUUKNF1guTuEfTRQ68QiX6wP6QPiBjEfYHMVL684qlGN/hbvDIa9QUA1PkKCLiBulV9rrs6BcxJkJeUzrHKgTvxh6tKSwh9kOGVWDIvLze/WCaMYAeOWJMcTwS0Gb88HB9Z+xEw36VIns+6oo4g4MV2Lmodcm/TAa+eWwdFIDN/A2CeVhP6CDtkez/ouHy0UV+o0tX89M82vJdILYsWlFUrAnXk9GIcGuD7o/0o20UPeslRSOoeXmGcdZl9skGtrQfuv2Qh36ySkVmfh7VHEDtkpymMWoGw27PRaqTTeqc40O07WjuaOpGEzkf8aWjuNo6vogFYJ4T/3ckFC7GuMsl71cB+3ZYYEnQb/gu/6fqcpB9TnAX6icRgGk7dgsfpnY=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

