apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgAGMKmxrKEZzmZt4TpdKLGuhvnoAEbbDaGJLwIiK7SkGq0TNF1uzzfe1Gf8kH3UQVOjCIO/WP4Ml6YtD4nNYYl/k8/aVP3ZLT8qFuMS4T6NNcK+EWFDlHK7pRaMyKw6vTdA2WcaEsZ8vyXNYBhTFNtgoD12S+K1aL5cVB/5X+OAPHcsfLkFTtzmw2qGvEQ9rtA+3QkooTGbtZ/kYXeL5fMXstT/LC1IzHPbdQwSfIBHAq0CniFR6vnVj2a7aXFEOI6gQdi4Lxc+xbNftyqZYGKlmLk7dAoqr9cMUTgHLkw0eWIQfd8Cn5/H/CbFvOpnl69u/BonE5fiQtzbUc1GAjB7cSAEZPfgbi02Mx6V4XbpO7qLMsSc3N2av2uJONGV8YnpAJwwuuPVQOp1P6/qdZ8O8GGGuCHT2+nzgxixUOqYhi0TsQENMvllFUy9akgk4JYyoA0LX8e7H8sZOZC96LJoOifP5agAZYCCH+O1zNx22vCu3ow2T8aZ+T0qNyLlEILuIcKCCEVf4w9i9kp2UD6acy3tUleEUwZq1iiu2zwV9ecpRA9nszUifv4AGRKhKkKO+HIaUaboj/2udvOjHZvxqLkfa+dIYvTsB8XhtQzwTiSt0g0WLN+NDBFcSMVJEmNcbMMZ/x405E4TODWF+zqCKdL+0WtTlsoBNlk14CocHvGavOADJpsIoD4zJ2qdOwPFgZG9I9baggylmXs2OTFzNGvUNAQEZObS0lr+XRnOgxFBGNnQsAt3TRmaU30n5vO5sx9XtKBIfx9pSVbEnz89xJTo1VMhAKWIjYvuQYTbMVYJBzYIIXDONnbN4Zt9wZAVE93+Vny+gaGR5SqII4n6pR+3ZBMDkG0fwh1jZhABrOynmTszraxCrcdCE6NvVBVDuhncO8JDyrSi3zQCJlY7NE54TUS6xB2f6MdTGeXDSZCu52TNZZ76e21JniEU14StjzS472K+ZSvOQMUB9cgKUjpy9v0/42IRJHcPyEK7MzFC8xz/u597a6Lok03/b8eTVFyBKj3/s90gK1ZxtPfefBuD8Cbhl5Q+tOI3jvdt6yR97+/bi/g1M1K0OrWbDoTjnl9ajKyVs/l0tBzcC5IXH1oySXPxoLsdqUw5rfW0pXGPZHpx3yZAZL/le3AcuskXAQdsaFFzNE/dEciOBx3CbIdWsx+o4xbL2ddFSnli/zfi
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

