apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgCIO2TyKPWdAYO9l30D1l2OjgmuvaSbxLa12tcmGnYIxfR1KrLqbj6Ul/DRrLK9bN39kaeUBp+mrCokX3BSY1ZAYv8dBfEVBoqEj48/r6FqpJet3Gsl2bGr7DK7hMl+ytgyS3MYU18A4s77/Cf2qvktiyqZ8IRgObDKJICDZFRSem9ow0UN+bnDqB+shs1gMGpT1188T13YBLMIMHxhWBQPonn6RF3RpsM8mg8E/8zwoJTtuqh7oLF8HdQ/IZNJ8jfGETGcva8d9p6hBYbGCeleK+6H9izHfkx7daBqtzjURFEo4JsMhGHfkfas/LZdq37PnsH7XaoCP9ty3vznlat5VIWq1zC4YVAFkCJwPnM36OkxKmjux4R5SJZELrC88vrm0ID+dFWGb8SMSICH6GCqeDm9T/gFDFAIwZtfRbqhhx/gcr0+PTbsPgljkL9a3SfV6HzzcYQj1YnxeA7iBCbb/8ZsreI7N+kiZfy9Wrwh2UXzVAL1DFhs4udnbF9r+g8hV58BhpLg0Bj2S/CO7vMHHOhSqCIW+iQbyQTq0TPD2kCi2e+D1gE6jqJMBjQPpiI8BNs2vahSqPwjG0ov3PbZdaaSzuivvQ1D2CBqPY8sZKUhWX134PfM4pkCWcCiShzCz1yXqWF2m1wbOgf0ZdfoSIDYDN2EEWQXAilFhf0CG+bMaMSssjN/P5shfoNerQ6OsxRDcJRGMXBtVNBi6kbj1y3Zcb7B+5YjStQDG3gsB/R7Oaxlz908ntC8MxIZEPQ6lMHjJtGNlvCO2eyxFxnQ7QkMEokwfovHnrl1GasjUlvVEhG3rjQl0l99S+NzIbb1N15eAhWesgwK+Yw1PKC7hZvgsin/TC0GpJICe9droD6DWBgX1z4wxVbTmZFVGamral1TafbylSHIHCtfasMFD52QrgfyVmNCmqCyOiHtqYvSwlVO0mPh2irxxnn5qsDBG3h5k7Duvl561WMGNXqPsF0YBljlOYfquki6V9ODkEdvrK+i2f+Ut04VB/hGiJPMCpl+wCV2YnVOLyl4kyPaCje9ZoxszQUYTJNHdCchERA87KeXar7sfblLGv9ihqR8ec5Ms35TTnwSGPoJ8Cr89tvwEcnwx6CsJzrt8gC/YI4V+W8=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

