apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgCdW5MicBFky7xIgq5b3Aq32M2FsBc+0Tie+1v+vfcLliX12VgXjokxOOZf0hqkgjAq1IyARynDLg5s9QttZvsNCWLtNkU18970ZruWtmzCKVcEM8tZCRKjRyi4UtWkIClSdgr211KquQYy+QzvZqqod8bYJgHtXqlL4QFO2GsTkvepTrZrCdvPxB+KlS5Kl57499C0BPh/0OVMEvfhkYhOG4dSrMhOCb6Y7fibQcioMh5SdJCqWtJ3jwmpa2REoHWpg74F6wWD4bG6GyyZZiJ3hcsytHg8Cl4wEBr4Xz/I72veh9ANDo6Ph9MKBq6MJiQS8Tvv8WKYeqGi9Vo+yNpIabCFYJs+kyUD7D6Z0Iziunseatio0OJZru7zoIXtENHyQ7RlLX0pab5BtKG24mVRpGlrBVU7htzaASRbhBeB8JvK4D9n8a+OGCR/MdwJac17WlBpJRYD7mxrg9b9AH2Tr8jpFI4cYXmlAnf5F0c5qLET6RnAXeYaUrM91bSpMjfyMltb6p/8x9Kt3jJF6/Bt75TyE4env7Ox6mPCBtxZ0x7F/eHwMNdI9z8YzHHZxQVaNRcavf5Od5eRlTx74Mtob/8eh52dpwGpR5BRJKW+9BUhYTuvfyU96sCgxg0B+Cey4mggwzWmcWbYeuIWGRzZr6ML7yw2HYXg8TxZcP7xqLkzrmwh6Gfxpf0PzcW1pGHGQ6KfTxK2eBTnxpNKRjRlYEA3yXDEYsyG83QfBR6XU8tVSVFZ13zkvYSCX/Qdatr+gRVKJ65VnWI63fP/8DpzzDq8qjARZdF5bBPULcGLCUWxFcyAKg6afJjCtkmP+s9cBUIIgK6vMjYILxUhikvUAOsASg9VZ+rj6rGhqeyjFuxKwGN/Sp76R97u1J3yqy1LKsOnzboTpO2KQlvFVGR/xPexxDC2eRcZs9gK6H9RCvZdQNfVRfIK1W8AHmvzuZaXLPCn5JUeSnokOuPrZWrmXmqkTHvMQRObaa+yqxHKv2hhpJ7xUzwd8E8gTLFbwTdJ4odTRmIDMhTP7O3GlUc/xlwGBoWlYkwDXIZg0+mBBvGnx9K6Rv4vU0ozDPfbJoorkt/3YkYX2gArp3NMDOz+tGmf7EJI5X4cvR8NcnAyGnCQ6q4=
  template:
    metadata:
      name: nextcloud
      namespace: nextcloud

