apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgCKQeJRqPsiMM+97PRqtn1V0a4ynSLuQD+g+Scm/nRVin6S8IuBXtb1U6rdy1MqYUwof+02wG4hjYtd2vs2fTD8QMlBMrjnweTul7xpJwSc07lkC6IxGsPNRVZ/sZabwzTehv86muLphkSDmNQQOlTVJ4qFHj9Mnohgg03x+2qDXK+wZtZbtQBsCk6rqKqNM0VIabrOwBN8TlnI0+fjuGuWPxSrshM0iFGZHcczjHseXw6ShijMVOabhuN5FmSuYnBfC/2Q1SznMEQ+hTQCDeMlb9Ta2BnJaksqRHyGZpAfSoBqK2xRtKgsGWuGF0FNT1b8WeDnlv4jbUF3Aac/wf/k91Bn6mIBJmI98SB/FoIwC6vkIerl92kLGQJB+Kr5rc7D8W/qD/qiLweG6xkowmsNyQNPDAbM05UdTHPut2sf62mrBFzMHyRDjoRC0iilNJGvm0h2AMPNuY8QqlB2Rz5JdtBQuYcbqpnH0bdLcEGAOZZ5gv3/zuBAI7VGlYNYSPp/74ggWIXp22V47mtsWzbqEVjRpVZ00ZJjhZilzsreZlQey10bIJMH5hQ5t45fKNOUal0200ThbjssXZfgAy/CWRs9uPH2bUVujMBeD7wc8OPsXRX+Jo2QDi0xvYzThbHGqn7hjn26raPg/GRtw2RsYTxK5xxwvWUDI+4+17PdXCY3jlNFThvS1WbxkRQmOO2cipyb9A3Iqdy2jd17921mCBt55SRfiGn4nGlzfe+b4snhxO7uDUwB0R11vkDXeynzTJYR8m/8qkP4OGpFxt+lLTwMmYkhlZPQGGtz5/8Gx/Bd7m+MUIP/32zNtxQbGXgvc1BXkDeDg7bAt189o8obelK7dIuKUVBDjX92wDHL4yYQAGd2bAXP/1WjSeR1NqUr+PXvsGsL5MNq788XzyovliCQHcjW03SfiM46E//tJmIR/N+Ol5OINPfIChJ5W6V2t6ntbQWSM2Udns5ae9rhchfauKoKRWq1zmwcRztJn2NJ5HZjOxlzS0KxuAn1htl3GfGuz/XIMGtbIQD5z/SkVGGgPvZtrFGdTtwwtb48B0gU3bTkPHNmWDlELrQw5hzXc+ka0AY834qxJDVNwgYmZA/ckw3cE2GReLmuSNqQSDgcn/o=
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

