apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  encryptedData:
    values.yaml: AgCDcipKEJQ9XqB/LhicDvkyGUDzEcSM/6dSUp4E/DXbsoJ6Ak+4ei/fgLIjbXJV1xXEaY4+ZXbMH6U+790z8iajXayfiSt3r+ViQQ94U+lNZ7SJUuQwFZ3V1PNqTyjoT/a26kdnQyhiXLCn7/DWAd+rcLVsbLWSj+N1/eXbb7U8DYUQ3riid1lMq/uh4pH2U/yA918Eix2pmkJ/xPoBnqKBWO3Xi7YO8zf0hCpw98+vdKyjxcetbnlpQz/d35PW+E0S/WP0xcPeCNcA2vl2vbyf8LViiQpyzHMzhI4xJXs1qH6J7axVTt39ioreYfdXu40fTzsziYEyIssgZDlInKWZ3TPZANeDo081jlQNPtWDQqLJFzM2Ixq52FcqdaKKPjhOZUYahDFNozJhqrT/xO1mCg+vaHiJDeTsooM5SxEaywbsjC3UvqssLs0hbjbHdGOEVBS8hiNN/D+XH8OMnrciDxy9E77Y76FFOKwewxEUy+YKyk3+HGNtWCRzU2ErNqiI1UyZOJMvGH9bKAEoUgUo/nLqxwtUR+w+rJ7hIsR76epfPH2jFDiMjLLr76sg7m57pabuQfZbsKqaS64+UJO0ZQ0NmqIFf4rzGqMYjRC6EHNeFnrITXCqCn/Qacx7FjYgeP1SsuMJo+aixxhaep6KjnfQgbOd4f+RQ2aJEzvj5MeqaXSchGSWkfi2Se0FZwtyi4hGt6tBjo2yLWm1JTAVHfkBU032yHtoTKKdc2N2ye/oBZWhp22nmaV6hEB65V8Mr8v9WmPUAO3MWuJ/es+HFhbrtrdeEJmu0WGPPbhHs1TthH7Ysm9U7NWNFYHFlfQHQZKCUoR2h5PTuspaecUKSYjcxdlWgZKN3fSrRnQnqlBuWvnZTBUSeSTIISiAxVegHfx7xRm/EqMgPQ44vUr4ayfI1CyjyZ+JGh12XUj+3kw45XojYnoGKK99CX2O6ies4zqmqyG4EPksVRJrSepiZQrqMvEo1DoHaRzGpNUKl1uwazB1VR9gXKvRfwLW/NodMtmReVTaq/poSJhqZ/uzpwLQwqXZH71PE6Kv/Ob0ttHuV3y22PnIfBsEBSErCi5Yfdxih5zCqUqMZ0bs9ukL4sC+Eoqs9URSEIr5mUnr6jwVJdufMhk4BIQlGzN6vzbuax0Nq13plvwucxPXnvKC
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-secrets
      namespace: nextcloud

