---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-nextcloud
spec:
  storageClassName: local-path
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/nfs/media/photos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-nextcloud
  namespace: nextcloud
spec:
  storageClassName: local-path
  volumeName: photos-nextcloud
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
