---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-nextcloud
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/databases/nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-nextcloud
  namespace: nextcloud
spec:
  storageClassName: local-path
  volumeName: database-nextcloud
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
