---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~0.12
    registry.fluxcd.io/sealed-secrets: quay.io
    repository.fluxcd.io/sealed-secrets: bitnami/sealed-secrets-controller
spec:
  test:
    enable: true
  rollback:
    enable: true
    retry: true
  releaseName: sealed-secrets
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: sealed-secrets
    version: 1.12.2
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.13.1
