---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jackett
  namespace: jackett
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: regex:^(version-v0\.[0-9]+\.[0-9]+$)
spec:
  test:
    enable: false
  rollback:
    enable: true
    retry: true
  releaseName: jackett
  chart:
    repository: https://k8s-at-home.com/charts/
    name: jackett
    version: 6.2.1
  values:
    image:
      repository: linuxserver/jackett
      tag: version-v0.17.242
    service:
      type: LoadBalancer
    persistence:
      config:
        enabled: true
      torrentblackhole:
        enabled: true
        existingClaim: jackett-torrents
