---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-torrents
spec:
  storageClassName: local-path
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/torrents
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-torrents
  namespace: jackett
spec:
  storageClassName: local-path
  volumeName: jackett-torrents
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
