---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: regex:alpine-v13\.[0-9]+\.[0-9]+$
    fluxcd.io/tag.runners: semver:~3
spec:
  test:
    enable: true
  rollback:
    enable: true
    retry: true
  releaseName: gitlab-runner
  chart:
    repository: https://charts.gitlab.io
    name: gitlab-runner
    version: 0.24.0
  valuesFrom:
  - secretKeyRef:
      name: gitlab-runner-secrets
  values:
    image: gitlab/gitlab-runner:alpine-v13.7.0
    gitlabUrl: https://git.soton.ac.uk
    rbac:
      create: true
      resources: ["pods", "pods/exec", "secrets"]
      verbs: ["get", "list", "watch", "create", "patch", "delete"]
      clusterWideAccess: false
    metrics:
      enabled: false
    runners:
      image: alpine:3.12.3
      locked: false
