apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner-secrets
  namespace: gitlab-runner
spec:
  encryptedData:
    values.yaml: AgCN95ppDsuI5HQ9e7698ry6x9+xWQiTVbU283GKjISVWAD0ATEwTFoaZIjkHfkQO69jpYjZdesjo2/r6BziPOuoQJZiVv/+OQzgwlovVabrq3iYPsEAtLgXc04sqRREEV+6b9VJRLxmREdLSs6F/9a9FspTCF9XaMPZJoiEjppCrZoSVgGf9cux3Cg8E60HbwtRUTTJmiVxRJXy/aTvwjIlFmN6KhMpIcSDtAtUIVC8+qGzSs/GPuTXtGV0G2DfhZHqEL6T2d5vYnDHHWAYSiN1zztaX+Ow+33t2bbV58RPjcmQ+5eyuR375DUWcD6haPXsL9rMlCrrpL5nCEF1ITLbH8/b/j5lak66DStAED4UZ5HR36FdlkXKQHbRcDwKhZoSH7IWjKipjTlfa6wXoDk4bcGPkgQnefPd8VhW115RL+c59cnHV8uK3w9+7mPu7SraBr49tDT+TPU1C3anQ6Br9JnirrpstfSUdpK8rDAenr+jTrxXstLy66GxRDd/JI/iKbhxxIMHB1kNTNpumVTRkxfE/bFvxLmzmV9ab9yY2dXpVu8DrmrgDscdOfm2nUhAdl2ccBY9mrM87J4w2McGyk8AClJhTtwCDoEd7eWeY/7bm9gg4OkSU2oV6e0P3TFPHCVYfTNv6rNG3KHx+ct2ZU0EoJQJJONQx03+lMmnC57wnwph2Wgpqavoz+xq8y68FAkWLXnUQfjhv/Ea6P79nnEc1HyLMl+QLOKrKv29urf1FOwt9LLMUQoxOipchPA=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner-secrets
      namespace: gitlab-runner

