apiVersion: v1
kind: Service
metadata:
  name: prosody
  namespace: prosody
spec:
  ports:
    - name: c2s
      port: 5222
      targetPort: 5222
    - name: s2s
      port: 5269
      targetPort: 5269
  type: LoadBalancer
  selector:
    app: prosody
status:
  loadBalancer: {}
