---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prosody-media
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /srv/smb/media/prosody-media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prosody-media
  namespace: prosody
spec:
  storageClassName: local-path
  volumeName: prosody-media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
