---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.controller: semver:*
    fluxcd.io/tag.speaker: semver:*
spec:
  test:
    enable: true
  rollback:
    enable: true
    retry: true
  releaseName: metallb
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: metallb
    version: 2.0.2
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.240-192.168.1.250
    controller:
      image:
        repository: bitnami/metallb-controller
        tag: 0.9.5
    speaker:
      image:
        repository: bitnami/metallb-speaker
        tag: 0.9.5
