apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: regex:10\.6.[0-9]+$
spec:
  test:
    enable: true
  rollback:
    enable: true
    retry: true
  releaseName: jellyfin
  chart:
    repository: https://k8s-at-home.com/charts/
    name: jellyfin
    version: 3.3.0
  values:
    image:
      repository: jellyfin/jellyfin
      tag: 10.6.4
    timezone: UTC+1
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      path: /
      hosts:
        - jellyfin.ssene.ca
      tls:
        - hosts:
            - jellyfin.ssene.ca
          secretName: jellyfin-tls-cert
    persistence:
      config:
        enabled: true
      additionalVolumes:
        - name: music
          persistentVolumeClaim:
            claimName: jellyfin-music
            readOnly: true
        - name: podcasts
          persistentVolumeClaim:
            claimName: jellyfin-podcasts
            readOnly: false
        - name: youtube
          persistentVolumeClaim:
            claimName: jellyfin-youtube
            readOnly: false
        - name: lectures
          persistentVolumeClaim:
            claimName: jellyfin-lectures
            readOnly: true
        - name: shows
          persistentVolumeClaim:
            claimName: jellyfin-shows
            readOnly: true
        - name: books
          persistentVolumeClaim:
            claimName: jellyfin-books
            readOnly: true
        - name: films
          persistentVolumeClaim:
            claimName: jellyfin-films
            readOnly: true
      additionalVolumeMounts:
        - name: music
          mountPath: "/mnt/music"
        - name: podcasts
          mountPath: "/mnt/podcasts"
        - name: youtube
          mountPath: "/mnt/youtube"
        - name: lectures
          mountPath: "/mnt/lectures"
        - name: shows
          mountPath: "/mnt/shows"
        - name: books
          mountPath: "/mnt/books"
        - name: films
          mountPath: "/mnt/films"
    resources:
      requests:
        gpu.intel.com/i915: 1
