---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: regex:10\.7.[0-9]+$
spec:
  test:
    enable: true
  rollback:
    enable: true
    retry: true
  releaseName: jellyfin
  chart:
    repository: https://k8s-at-home.com/charts/
    name: jellyfin
    version: 5.1.0
  values:
    image:
      repository: jellyfin/jellyfin
      tag: 10.7.3
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - host: jellyfin.ssene.ca
        paths:
        - path: /
      tls:
      - hosts:
        - jellyfin.ssene.ca
        secretName: jellyfin-tls-cert
    persistence:
      config:
        enabled: true
    additionalVolumes:
    - name: music
      persistentVolumeClaim:
        claimName: jellyfin-music
        readOnly: true
    - name: podcasts
      persistentVolumeClaim:
        claimName: jellyfin-podcasts
        readOnly: false
    - name: youtube
      persistentVolumeClaim:
        claimName: jellyfin-youtube
        readOnly: false
    - name: lectures
      persistentVolumeClaim:
        claimName: jellyfin-lectures
        readOnly: true
    - name: shows
      persistentVolumeClaim:
        claimName: jellyfin-shows
        readOnly: true
    - name: books
      persistentVolumeClaim:
        claimName: jellyfin-books
        readOnly: true
    - name: movies
      persistentVolumeClaim:
        claimName: jellyfin-movies
        readOnly: true
    additionalVolumeMounts:
    - name: music
      mountPath: "/mnt/music"
    - name: podcasts
      mountPath: "/mnt/podcasts"
    - name: youtube
      mountPath: "/mnt/youtube"
    - name: lectures
      mountPath: "/mnt/lectures"
    - name: shows
      mountPath: "/mnt/shows"
    - name: books
      mountPath: "/mnt/books"
    - name: movies
      mountPath: "/mnt/movies"
    resources:
      limits:
        gpu.intel.com/i915: 1
