apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.ingress-nginx: semver:*
spec:
  test:
    enable: true
  rollback:
    enable: true
    retry: true
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.3.0
  values:
    controller:
      image:
        repository: k8s.gcr.io/ingress-nginx/controller
