apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: regex:v0\.4[0-9]\.[0-9]$
spec:
  test:
    enable: true
  rollback:
    enable: true
    retry: true
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.30.0
  values:
    controller:
      image:
        repository: k8s.gcr.io/ingress-nginx/controller
        tag: v0.46.0
