apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB9L7Tj4MqlkRa+xUFJ1a+fPcJ3NNT7Teq2f8ClxMtncnFtqUrh/QvrSgWOJzmy12HDIovxR6hzjIarbrgUzoXm7+D40XgrqczLykS73zI63BfQq2lM/mzOASXOum9uMkl1IHKGTPfuYYMZM77kzmbz449LSG0fldjLf01SZund/su53TRdiOAIMNzFjuW+9qXsxlK5f/EzsY2feqydKFIU6bRKrL7YX9C544/FjtqZL4yZqO3EEj8ngVMgH+uTziUIbd6ryqgJFu94YvjNogObvEaOma1ekEQdR3BT5Tjs5Ngm53nheuJsqrT0hb0SiG+F3+OqNjwz3DFCQO5VjK++KoOPt0Tk7Jol9dFaD1Cq/irQSkU7FxG6HczBXZwsh+YU5dVkYKkpS7te6er72jBiioR/bla/6yf8gf0EiAKdZxYSgPeOaeLQqk9WDK2S6T83FD+7llXqZQnaamIK2vFoJwb1EPmowyEQAKZkqfvO/V57/5uuex2AkeNZYeruLjZzus+hqtx+cuTYMjl1Fa1qwOYCQRE5rJt64vLUDFPly2C0MrQGE1nxtMr5S711K+gSJEUylsniJbOUMlha5nHc99WZBHkoBsBRgggONvfbUXYIvf4oPQTDCmJLS+KB3UvPk1dsKVcktzIXxA5tlvXqPFThfROu/X3CWbKR1/nbpyHNPz1RMwJEigQ4EWByngg1tWT0SUatfWgpn2oa28HbWm1xHxkKuW/5hECft07VvmrTVsG3P5zo
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

