apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.cert-manager: glob:v*.*.*
    fluxcd.io/tag.cert-manager-webhook: glob:v*.*.*
    fluxcd.io/tag.cert-manager-cainjector: glob:v*.*.*
spec:
  test:
    enable: true
  rollback:
    enable: true
    retry: true
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.0.2
  values:
    installCRDs: true
    image:
      registry: quay.io
      repository: jetstack/cert-manager-controller
    webhook:
      image:
        registry: quay.io
        repository: jetstack/cert-manager-webhook
    cainjector:
      image:
        registry: quay.io
        repository: jetstack/cert-manager-cainjector
