---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1
    fluxcd.io/tag.webhook: semver:~1
    fluxcd.io/tag.cainjector: semver:~1
spec:
  test:
    enable: true
  rollback:
    enable: true
    retry: true
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.0.2
  values:
    installCRDs: true
    image:
      registry: quay.io
      repository: jetstack/cert-manager-controller
      tag: v1.0.4
    webhook:
      image:
        registry: quay.io
        repository: jetstack/cert-manager-webhook
        tag: v1.0.3
    cainjector:
      image:
        registry: quay.io
        repository: jetstack/cert-manager-cainjector
        tag: v1.0.4
